:Author: Dunadan
:Email: grigor.tonikyan@gmail.com
:Date: 24/08/2018
:Revision: version#
:License: Public Domain

= Project: {Project}

Simple Arduino sketch to control up to 256 power elements ( relays pr MOSFETs ) using Adafruit PCA9685 16-Channel Servo Drivers chained on I2C bus (up to 16 )
This sketch dont include ability to control incremental PWM values for each element (it is wrote for relays) but some minor modifications can achive that.
Control is done using serial interface from PC, just send numbers on serial last digit of number is state of elemnt ( 0 for off, 1 for on, and 8 to turn on all elements on set board)

== Step 1: Installation
you will need to install 
Adafruit-PWM-Servo-Driver-Library


== Step 2: Assemble the circuit
refer to Adafruit PCA9685 16-Channel Servo Drivers guide

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact Dunadan <grigor.tonikyan@gmail.com>


